apiVersion: v1
kind: Config
clusters:
- name: "compass-qa"
  cluster:
    server: "https://chqrancher.clearent.net/k8s/clusters/c-95tc8"
- name: "compass-qa-chqqacmprnch01"
  cluster:
    server: "https://172.16.18.155:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl3TURZd016RTFORFkxTVZvWERUTXdNRFl3TVRFMU5EWTFNVm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQVAzYlFzZ2pKTHBxCktnWHVZK3BoOVpweW42NUFTVXFDWnVKT3hBMXl5WTN1dHd4bFFxQU42a\
      HJSdjVOMVVzY0Q5dGpIOGVjTVFEeTAKR28wNDdyMW9rQ2U4bWgrcHJEcHdKWk4vQjFHVkkyTVJaS\
      zd6WC93QUpJVWp1Y1RxckNGV0lEa0t5eVc0cUJCUwp5TjI1OTRMUUtqSDBiSWE0dkRTbnRiOU9CV\
      ldZV0NuY1p2R0U4QkxIalB5K2xqZHpOZDdsN2MwZDBUN3FOY3Q1CjBhakJsYWFkMEVxZHdkOHU4M\
      0diaGxleTJGSTkyUmlwSnlRakFPd2Y1NGhvMlJHOFlPTmhuNTVYQVl4c0JoR1QKcm8vM2JiZWE1R\
      3cxUHc1M05PQ1ZLTHNnWU5lcnhiTCtMZkNQbEJDdFZ2OGM0aDBRc3pOaEZvMnlxcHdIaXYzYQpVY\
      Xh0UUl3OVN6c0NBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSHRmR0FhQ0pUYmlzd3laRHJDbDFUM\
      HlPQmVWbzFhbHd5Sm0KajZBYStPdWErVkxEcGloNENZN2d1WHZrVGo5QWlDRkFWT2J2VWpxSHgvL\
      24yeENqNStMMmVIUCtkUVBPa2xuZApoSG5XRVdoL2NxSTlTM2Y4dk1VcWlrZHpmNDV3dVBqd3Bme\
      lF5OFREL3JkdDNndkRzSThvemtJREVIaC9jVGtCCnR1dFV2UHlDZFpYeVUyTzVndzhYMTN4ZXhsR\
      WowWS9DTDMyOFFUbU9pV2NCKzAxSWRkUHZUZklpT0hRLzhRRHcKVTlHL3RDV1Vka1lLYS9FVGZoR\
      zZTYUVwYzMxakZ0OVNWUzB6cXNKd3ZWbFpsd3hOOGphenlzVGVHdXg4czZWMgpxaGRUaTBHNzZlY\
      jlhNW12bFRXaUw3cmJ0MHpXVVJ2RS9BZ0xiRVBQUnZuMGdmbVUwbjA9Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"
- name: "compass-qa-chqqacmprnch03"
  cluster:
    server: "https://172.16.18.157:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl3TURZd016RTFORFkxTVZvWERUTXdNRFl3TVRFMU5EWTFNVm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQVAzYlFzZ2pKTHBxCktnWHVZK3BoOVpweW42NUFTVXFDWnVKT3hBMXl5WTN1dHd4bFFxQU42a\
      HJSdjVOMVVzY0Q5dGpIOGVjTVFEeTAKR28wNDdyMW9rQ2U4bWgrcHJEcHdKWk4vQjFHVkkyTVJaS\
      zd6WC93QUpJVWp1Y1RxckNGV0lEa0t5eVc0cUJCUwp5TjI1OTRMUUtqSDBiSWE0dkRTbnRiOU9CV\
      ldZV0NuY1p2R0U4QkxIalB5K2xqZHpOZDdsN2MwZDBUN3FOY3Q1CjBhakJsYWFkMEVxZHdkOHU4M\
      0diaGxleTJGSTkyUmlwSnlRakFPd2Y1NGhvMlJHOFlPTmhuNTVYQVl4c0JoR1QKcm8vM2JiZWE1R\
      3cxUHc1M05PQ1ZLTHNnWU5lcnhiTCtMZkNQbEJDdFZ2OGM0aDBRc3pOaEZvMnlxcHdIaXYzYQpVY\
      Xh0UUl3OVN6c0NBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSHRmR0FhQ0pUYmlzd3laRHJDbDFUM\
      HlPQmVWbzFhbHd5Sm0KajZBYStPdWErVkxEcGloNENZN2d1WHZrVGo5QWlDRkFWT2J2VWpxSHgvL\
      24yeENqNStMMmVIUCtkUVBPa2xuZApoSG5XRVdoL2NxSTlTM2Y4dk1VcWlrZHpmNDV3dVBqd3Bme\
      lF5OFREL3JkdDNndkRzSThvemtJREVIaC9jVGtCCnR1dFV2UHlDZFpYeVUyTzVndzhYMTN4ZXhsR\
      WowWS9DTDMyOFFUbU9pV2NCKzAxSWRkUHZUZklpT0hRLzhRRHcKVTlHL3RDV1Vka1lLYS9FVGZoR\
      zZTYUVwYzMxakZ0OVNWUzB6cXNKd3ZWbFpsd3hOOGphenlzVGVHdXg4czZWMgpxaGRUaTBHNzZlY\
      jlhNW12bFRXaUw3cmJ0MHpXVVJ2RS9BZ0xiRVBQUnZuMGdmbVUwbjA9Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"
- name: "compass-qa-chqqacmprnch02"
  cluster:
    server: "https://172.16.18.156:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl3TURZd016RTFORFkxTVZvWERUTXdNRFl3TVRFMU5EWTFNVm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQVAzYlFzZ2pKTHBxCktnWHVZK3BoOVpweW42NUFTVXFDWnVKT3hBMXl5WTN1dHd4bFFxQU42a\
      HJSdjVOMVVzY0Q5dGpIOGVjTVFEeTAKR28wNDdyMW9rQ2U4bWgrcHJEcHdKWk4vQjFHVkkyTVJaS\
      zd6WC93QUpJVWp1Y1RxckNGV0lEa0t5eVc0cUJCUwp5TjI1OTRMUUtqSDBiSWE0dkRTbnRiOU9CV\
      ldZV0NuY1p2R0U4QkxIalB5K2xqZHpOZDdsN2MwZDBUN3FOY3Q1CjBhakJsYWFkMEVxZHdkOHU4M\
      0diaGxleTJGSTkyUmlwSnlRakFPd2Y1NGhvMlJHOFlPTmhuNTVYQVl4c0JoR1QKcm8vM2JiZWE1R\
      3cxUHc1M05PQ1ZLTHNnWU5lcnhiTCtMZkNQbEJDdFZ2OGM0aDBRc3pOaEZvMnlxcHdIaXYzYQpVY\
      Xh0UUl3OVN6c0NBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSHRmR0FhQ0pUYmlzd3laRHJDbDFUM\
      HlPQmVWbzFhbHd5Sm0KajZBYStPdWErVkxEcGloNENZN2d1WHZrVGo5QWlDRkFWT2J2VWpxSHgvL\
      24yeENqNStMMmVIUCtkUVBPa2xuZApoSG5XRVdoL2NxSTlTM2Y4dk1VcWlrZHpmNDV3dVBqd3Bme\
      lF5OFREL3JkdDNndkRzSThvemtJREVIaC9jVGtCCnR1dFV2UHlDZFpYeVUyTzVndzhYMTN4ZXhsR\
      WowWS9DTDMyOFFUbU9pV2NCKzAxSWRkUHZUZklpT0hRLzhRRHcKVTlHL3RDV1Vka1lLYS9FVGZoR\
      zZTYUVwYzMxakZ0OVNWUzB6cXNKd3ZWbFpsd3hOOGphenlzVGVHdXg4czZWMgpxaGRUaTBHNzZlY\
      jlhNW12bFRXaUw3cmJ0MHpXVVJ2RS9BZ0xiRVBQUnZuMGdmbVUwbjA9Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"

users:
- name: "compass-qa"
  user:
    token: "kubeconfig-user-5bncz.c-95tc8:mnnxg84wz4h88bvr62n4cvmp46jn6qvnt8786vznbnshtls5fs77t7"

contexts:
- name: "compass-qa"
  context:
    user: "compass-qa"
    cluster: "compass-qa"
- name: "compass-qa-chqqacmprnch01"
  context:
    user: "compass-qa"
    cluster: "compass-qa-chqqacmprnch01"
- name: "compass-qa-chqqacmprnch03"
  context:
    user: "compass-qa"
    cluster: "compass-qa-chqqacmprnch03"
- name: "compass-qa-chqqacmprnch02"
  context:
    user: "compass-qa"
    cluster: "compass-qa-chqqacmprnch02"

current-context: "compass-qa"
