apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-class-a-edocs-api
  name: edocs-api
  namespace: class-a
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-class-a-edocs-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-class-a-edocs-api
    spec:
      containers:
      - env:
        - name: KRB5_CLIENT_KTNAME
          value: /app/keys/horizon.keytab
        - name: KRB5_CONFIG
          value: /app/keys/krb5.conf
        image: cladocreg01.clearent.net/settlement/edocs-api:20191212.22.8.48-T31200-TUPrintImage
        livenessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Host
              value: edocs-v2-dev.clearent.net
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        name: edocs-api
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Host
              value: edocs-v2-dev.clearent.net
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 2
        resources: {}
        volumeMounts:
        - mountPath: /app/config
          name: configs
        - mountPath: /app/keys
          name: keys
      imagePullSecrets:
        - name: harbor
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 256
          name: configs
          optional: false
        name: config
      - name: keys
        secret:
          defaultMode: 256
          optional: false
          secretName: keys
status: {}
