apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-class-a-electronic-signature-web
  name: electronic-signature-web
  namespace: class-a
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-class-a-electronic-signature-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-class-a-electronic-signature-web
    spec:
      containers:
      - env:
        - name: KRB5_CLIENT_KTNAME
          value: /app/keys/horizon.keytab
        - name: KRB5_CONFIG
          value: /app/keys/krb5.conf
        image: cladocreg01.clearent.net/settlement/electronic-signature-web:20190730.20.22.28-T28718-Antiforgery
        name: electronic-signature-web
        livenessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Host
              value: electronic-signature-web
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Host
              value: electronic-signature-web
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 2
        resources: {}
        volumeMounts:
        - mountPath: /app/config
          name: configs
      imagePullSecrets:
        - name: harbor
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 256
          name: configs
          optional: false
        name: config
status: {}
