apiVersion: v1
kind: Config
clusters:
- name: "compass-dev"
  cluster:
    server: "https://chqrancher.clearent.net/k8s/clusters/c-zb97k"
- name: "compass-dev-chqdevcmprnch03"
  cluster:
    server: "https://172.16.1.157:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl3TURFeU9ERTVNREl6TkZvWERUTXdNREV5TlRFNU1ESXpORm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU5sTTFSYTBXb2hkCnVQS1FnRnNobFN5c2VrdGFsUG8zU1VIUmZhL0RhZWJaY0NIZ05ZVXZuU\
      0xjRUQ3OWRxZzRHWVNrN1FBTlhwUDgKSFY4bk13K3BEWVRDTGFJSEVuQTBaVzRsSDJSOVdRT08yL\
      2tCT0JEQ3QxbWhLMDVwYmdBdjFLdTRUcktDcmtISApna2E3UUx4eE40UG5JVlJGODBOTWtBa0NxV\
      klmVENNZjgweVBWdG9pdkhFRGRENkdxVFBpaVZxNkdLNFdBMDBSCjlrc1V0cms4eFlnZW9rUEkxS\
      GNoTlY5bkwvZlhXaWpKNmJ6RVJ3Vm9HOGhLVGpxcTRtb24wVkFudzA3NElubVoKOFRkenQ1SVFNS\
      2hZS1BXVWFDT05JdmhLanNjN3NOd1F4NGU2ZDBsVVQyRmQvWnU4OGMwYmFVR1orZmFWdWk4eApmM\
      Hhiajc2U2c4a0NBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRjFtSkUrcU5oUmtkZzBGNnJ5VlFuR\
      2tNT0drQmV6bnRjRjYKOVd6OE1IMnRkTnhjaXdnd1BXZzdaamZKRkxZMkdKbDZSNEtubzcrM3ZMZ\
      HJMOVFsTW5IVlpQSko1eFg0VDltUwpvN09lRFk1S3FSajBrdXF3QVYxQ2dxb2V5U25vWFRpbUlmT\
      zJUbHpZQkpVb2VyTWhTdVY1ZC84TEIvUkRzNFBBCktwZTdNSlFiTnFBOGk2OWloVHRVQXk5aHZab\
      StJMEtjQUVhYmxZTzAzaG5SQTlOcEp4dHlYOS9QbHhzeFdJREMKMXFIVTNvblJmdlJaTE5MaTBhT\
      jF1OUVtTmIxdFJpdDlwbGhoVEh6Wkp1S2NVWEhLN3RONmpOWmZ5dVlkNWFqMgppMTZ4dFFPWk5Wc\
      HYzdTI5UUlNY1FYZFpqdW1vRklMMytKaTVRS2lRN0xzd3plejlpMEE9Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"
- name: "compass-dev-chqdevcmprnch02"
  cluster:
    server: "https://172.16.1.156:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl3TURFeU9ERTVNREl6TkZvWERUTXdNREV5TlRFNU1ESXpORm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU5sTTFSYTBXb2hkCnVQS1FnRnNobFN5c2VrdGFsUG8zU1VIUmZhL0RhZWJaY0NIZ05ZVXZuU\
      0xjRUQ3OWRxZzRHWVNrN1FBTlhwUDgKSFY4bk13K3BEWVRDTGFJSEVuQTBaVzRsSDJSOVdRT08yL\
      2tCT0JEQ3QxbWhLMDVwYmdBdjFLdTRUcktDcmtISApna2E3UUx4eE40UG5JVlJGODBOTWtBa0NxV\
      klmVENNZjgweVBWdG9pdkhFRGRENkdxVFBpaVZxNkdLNFdBMDBSCjlrc1V0cms4eFlnZW9rUEkxS\
      GNoTlY5bkwvZlhXaWpKNmJ6RVJ3Vm9HOGhLVGpxcTRtb24wVkFudzA3NElubVoKOFRkenQ1SVFNS\
      2hZS1BXVWFDT05JdmhLanNjN3NOd1F4NGU2ZDBsVVQyRmQvWnU4OGMwYmFVR1orZmFWdWk4eApmM\
      Hhiajc2U2c4a0NBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRjFtSkUrcU5oUmtkZzBGNnJ5VlFuR\
      2tNT0drQmV6bnRjRjYKOVd6OE1IMnRkTnhjaXdnd1BXZzdaamZKRkxZMkdKbDZSNEtubzcrM3ZMZ\
      HJMOVFsTW5IVlpQSko1eFg0VDltUwpvN09lRFk1S3FSajBrdXF3QVYxQ2dxb2V5U25vWFRpbUlmT\
      zJUbHpZQkpVb2VyTWhTdVY1ZC84TEIvUkRzNFBBCktwZTdNSlFiTnFBOGk2OWloVHRVQXk5aHZab\
      StJMEtjQUVhYmxZTzAzaG5SQTlOcEp4dHlYOS9QbHhzeFdJREMKMXFIVTNvblJmdlJaTE5MaTBhT\
      jF1OUVtTmIxdFJpdDlwbGhoVEh6Wkp1S2NVWEhLN3RONmpOWmZ5dVlkNWFqMgppMTZ4dFFPWk5Wc\
      HYzdTI5UUlNY1FYZFpqdW1vRklMMytKaTVRS2lRN0xzd3plejlpMEE9Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"
- name: "compass-dev-chqdevcmprnch01"
  cluster:
    server: "https://172.16.1.155:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl3TURFeU9ERTVNREl6TkZvWERUTXdNREV5TlRFNU1ESXpORm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU5sTTFSYTBXb2hkCnVQS1FnRnNobFN5c2VrdGFsUG8zU1VIUmZhL0RhZWJaY0NIZ05ZVXZuU\
      0xjRUQ3OWRxZzRHWVNrN1FBTlhwUDgKSFY4bk13K3BEWVRDTGFJSEVuQTBaVzRsSDJSOVdRT08yL\
      2tCT0JEQ3QxbWhLMDVwYmdBdjFLdTRUcktDcmtISApna2E3UUx4eE40UG5JVlJGODBOTWtBa0NxV\
      klmVENNZjgweVBWdG9pdkhFRGRENkdxVFBpaVZxNkdLNFdBMDBSCjlrc1V0cms4eFlnZW9rUEkxS\
      GNoTlY5bkwvZlhXaWpKNmJ6RVJ3Vm9HOGhLVGpxcTRtb24wVkFudzA3NElubVoKOFRkenQ1SVFNS\
      2hZS1BXVWFDT05JdmhLanNjN3NOd1F4NGU2ZDBsVVQyRmQvWnU4OGMwYmFVR1orZmFWdWk4eApmM\
      Hhiajc2U2c4a0NBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRjFtSkUrcU5oUmtkZzBGNnJ5VlFuR\
      2tNT0drQmV6bnRjRjYKOVd6OE1IMnRkTnhjaXdnd1BXZzdaamZKRkxZMkdKbDZSNEtubzcrM3ZMZ\
      HJMOVFsTW5IVlpQSko1eFg0VDltUwpvN09lRFk1S3FSajBrdXF3QVYxQ2dxb2V5U25vWFRpbUlmT\
      zJUbHpZQkpVb2VyTWhTdVY1ZC84TEIvUkRzNFBBCktwZTdNSlFiTnFBOGk2OWloVHRVQXk5aHZab\
      StJMEtjQUVhYmxZTzAzaG5SQTlOcEp4dHlYOS9QbHhzeFdJREMKMXFIVTNvblJmdlJaTE5MaTBhT\
      jF1OUVtTmIxdFJpdDlwbGhoVEh6Wkp1S2NVWEhLN3RONmpOWmZ5dVlkNWFqMgppMTZ4dFFPWk5Wc\
      HYzdTI5UUlNY1FYZFpqdW1vRklMMytKaTVRS2lRN0xzd3plejlpMEE9Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"

users:
- name: "compass-dev"
  user:
    token: "kubeconfig-user-5bncz.c-zb97k:q2cntvftkt4hz6m5wbfr7z6j8tndxb8s65sw8b542ns6bzhp7f6zlj"

contexts:
- name: "compass-dev"
  context:
    user: "compass-dev"
    cluster: "compass-dev"
- name: "compass-dev-chqdevcmprnch03"
  context:
    user: "compass-dev"
    cluster: "compass-dev-chqdevcmprnch03"
- name: "compass-dev-chqdevcmprnch02"
  context:
    user: "compass-dev"
    cluster: "compass-dev-chqdevcmprnch02"
- name: "compass-dev-chqdevcmprnch01"
  context:
    user: "compass-dev"
    cluster: "compass-dev-chqdevcmprnch01"

current-context: "compass-dev"
