apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-class-c-pricing-analysis-web
  name: pricing-analysis-web
  namespace: class-c
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-class-c-pricing-analysis-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-class-c-pricing-analysis-web
    spec:
      containers:
      - env:
        - name: KRB5_CLIENT_KTNAME
          value: /app/keys/pricing.keytab
        - name: KRB5_CONFIG
          value: /app/keys/krb5.conf
        image: cladocreg01.clearent.net/settlement/pricing-analysis-web:11902
        name: pricing-analysis-web
        livenessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Host
              value: pricing-analysis-web
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Host
              value: pricing-analysis-web
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 2
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/nginx/html/assets/data/PricingAnalysisClientConfig.json
          name: config
          readOnly: true
          subPath: PricingAnalysisClientConfig.json
      imagePullSecrets:
        - name: harbor
      restartPolicy: Always
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: class-c-settlementconfigurations
status: {}
