apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-class-a-rbt
  name: bulkpricingapi
  namespace: class-b
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-class-a-rbt
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-class-a-rbt
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFINITIONS_FILE
          value: /etc/rabbitmq/definitions.json
        - name: RABBITMQ_ERLANG_COOKIE
          value: KVRQPRCJHEAWGGKLLUAZ
        image: cladocreg01.clearent.net/settlement/rabbit:374.1
        name: rbt
        resources: {}
        volumeMounts:
        - mountPath: /etc/rabbitmq/definitions.json
          name: definitions
        - mountPath: /etc/rabbitmq/rabbitmq.conf
          name: conf
      imagePullSecrets:
        - name: harbor
      restartPolicy: Always
      volumes:
      - name: definitions
        hostPath:
          path: /opt/docker/rabbit-cluster/definitions.json
      - name: conf
        hostPath:
          path: /opt/docker/rabbit-cluster/rabbitmq.conf
status: {}
