apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-class-c-tinvalidation
  name: tinvalidation
  namespace: class-c
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      job-name: tinvalidation
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: tinvalidation
    spec:
      containers:
      - env:
        - name: KRB5_CLIENT_KTNAME
          value: /app/keys/enaslund.keytab
        - name: KRB5_CONFIG
          value: /app/keys/krb5.conf
        image: cladocreg01.clearent.net/settlement/tinvalidation:0.6
        name: tinvalidation
        resources: {}
        volumeMounts:
        - mountPath: /app/config
          name: configs
        - mountPath: /app/keys
          name: keys
      imagePullSecrets:
        - name: harbor
      restartPolicy: Never
      volumes:
      - name: configs
        hostPath:
          path: /git/SettlementConfigurations/DEV
      - name: keys
        hostPath:
          path: /git/keys
status: {}
