apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-class-a-underwriting-results-web
  name: underwriting-results-web
  namespace: class-a
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-class-a-underwriting-results-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-class-a-underwriting-results-web
    spec:
      containers:
      - env:
        - name: KRB5_CLIENT_KTNAME
          value: /app/keys/sqlauth.keytab
        - name: KRB5_CONFIG
          value: /app/keys/krb5.conf
        image: cladocreg01.clearent.net/settlement/underwriting-results-web:20191210.16.43.54-T31719-UseNginxAlpine
        livenessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Host
              value: underwriting-results-web
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        name: underwriting-results-web
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Host
              value: underwriting-results-web
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 2
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/nginx/html/underwritingwebapp/assets/data/UnderwritingResultsClientConfig.json
          name: config
          readOnly: true
          subPath: UnderwritingResultsClientConfig.json
      imagePullSecrets:
        - name: harbor
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 256
          items:
          - key: UnderwritingResultsClientConfig.json
            path: UnderwritingResultsClientConfig.json
          name: configs
          optional: false
        name: config
status: {}
